---
  - name: Copy config file to httpd config location
    copy:
      src: httpd.conf
      dest: /etc/httpd/conf/httpd.conf
      owner: root
      group: root
      mode: 0644
    notify: restart apache service
...
