--- # Demonstration of more details about tasks execution (debug)
- hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name: "Install telnet package on localhosts"
    yum:
      name: telnet
      state: latest
    register: result
  - debug: var=result
